image: node:6.1.0

services:
  - trevorhanus/dynamodb-local:latest

all_tests:
  script:
   - npm install
   - npm run test-once

pages:
  image: devunix/alpine-mkdocs
  script:
  - mkdocs build
  artifacts:
    paths:
    - site
    