site_name: Dynanode
theme: readthedocs
pages:
  - Home: index.md
  - Tables:
    - Create Table: tables/createTable.md
    - Delete Table: tables/deleteTable.md
    - Describe Table: tables/describeTable.md
  - Working with Items:
    - Overview: items/overview.md
    - Get: items/getItem.md
    - Insert: items/insertItem.md
    - Update: items/updateItem.md
    - Conditionally Update: items/conditionallyUpdate.md
    - Increment a Counter (na): items/incrementCounter.md
    - Batch Write (na): items/batchWrite.md
    - Batch Get (na): items/batchGet.md
    - Create Set (na): items/createSet.md
  - Params:
    - Overview: params/overview.md
    - .attrs(): params/attrs.md
    - .if(): params/if.md
    - .consistentRead(): params/consistentRead.md