site_name: Dynanode
theme: readthedocs
pages:
  - Home: index.md
  - Getting Started:
    - Install: getting-started/install.md
    - Use: getting-started/use.md
  - Working with Items:
    - Overview: items/overview.md
    - Get: items/getItem.md
    - Put: items/putItem.md
    - Update: items/updateItem.md
    - Conditionally Update: items/conditionallyUpdate.md
    - Increment a Counter (future): items/incrementCounter.md
    - Batch Write (future): items/batchWrite.md
    - Batch Get (future): items/batchGet.md
    - Create Set (future): items/createSet.md
  - Params:
    - Overview: params/overview.md
    - .attrs(): params/attrs.md
    - .where(): params/where.md
    - .consistentRead(): params/consistentRead.md
    - .returnConsumedCapacity(): params/consumedCapacity.md
  - Tables:
    - Create Table: tables/createTable.md
    - Delete Table: tables/deleteTable.md
    - Describe Table: tables/describeTable.md