site_name: Dynaflo
theme: readthedocs
pages:
  - Home: index.md
  - Quick Start: quickStart.md
  - Methods:
    - Get: methods/getItem.md
    - Put: methods/putItem.md
    - Update: methods/updateItem.md
    - Delete: methods/deleteItem.md
    - Query: methods/query.md
    - Batch Write: methods/batchWrite.md
    - Batch Get (future): methods/batchGet.md
  - Method Modifiers:
    - Overview: params/overview.md
    - .pluck(): modifiers/pluck.md
    - .where(): modifiers/where.md
    - .when(): modifiers/when.md
  - Conditions:
    - .eq(): comparators/equal.md
    - .ne(): comparators/notEqual.md
    - .lt(): comparators/lessThan.md
    - .le(): comparators/lessThanEqual.md
    - .gt(): comparators/greaterThan.md
    - .ge(): comparators/greaterThanEqual.md
    - .between(): comparators/between.md
    - .in(): comparators/in.md
    - .exists(): comparators/exists.md
    - .notExists(): comparators/notExists.md
    - .type(): comparators/type.md
    - .beginsWith(): comparators/beginsWith.md
    - .contains(): comparators/contains.md
    - .size() (future): comparators/size.md
  - Working with Tables:
    - Create Table: tables/createTable.md
    - Delete Table: tables/deleteTable.md
    - Describe Table: tables/describeTable.md
