site_name: Dynaflo
theme: readthedocs
pages:
  - Home: index.md
  - Getting Started:
    - Install: getting-started/install.md
    - Use: getting-started/use.md
  - Working with Items:
    - Get: items/getItem.md
    - Put: items/putItem.md
    - Update: items/updateItem.md
    - Delete: items/deleteItem.md
    - Query: items/query.md
    - Batch Write (future): items/batchWrite.md
    - Batch Get (future): items/batchGet.md
  - Modifiers:
    - Overview: params/overview.md
    - .pluck(): modifiers/pluck.md
    - .where(): modifiers/where.md
    - .when(): modifiers/when.md
  - Comparators:
    - .eq(): comparators/equal.md
    - .ne(): comparators/notEqual.md
    - .lt(): comparators/lessThan.md
    - .le(): comparators/lessThanEqual.md
    - .gt(): comparators/greaterThan.md
    - .ge(): comparators/greaterThanEqual.md
    - .between(): comparators/between.md
    - .in(): comparators/in.md
    - .exists(): comparators/exists.md
    - .notExists(): comparators/notExists.md
    - .type(): comparators/type.md
    - .beginsWith(): comparators/beginsWith.md
    - .contains(): comparators/contains.md
    - .size() (future): comparators/size.md
  - Tables:
    - Create Table: tables/createTable.md
    - Delete Table: tables/deleteTable.md
    - Describe Table: tables/describeTable.md